version: '3'
services:
  reactapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app  
    environment:
      - CHOKIDAR_USEPOLLING=true

  reactapptest:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app  
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm","run","test"]

